import type { Copy } from './index'

/**
 * English UI copy. Must conform to `Copy` — a missing key is a compile error.
 * Most of this is lifted verbatim from the v3 prototypes, which is where the
 * tone was worked out; don't "improve" it without a reason.
 */
export const en: Copy = {
  app: {
    name: 'BAB',
    tagline: 'Learn to read your own signals',
  },

  langName: 'English',

  tabs: {
    today: 'Today',
    journey: 'Journey',
    me: 'Me',
    ariaLabel: 'Main navigation',
  },

  flow: {
    next: 'Next',
    back: 'Back',
    close: 'Close',
    skip: 'Skip this one',
    progress: 'How far you are',
    leaveTitle: 'Leave the check-in?',
    leaveBody: "What you've answered so far isn't saved yet: it all saves together at the end. Leave now and you lose it.",
    leaveYes: 'Leave and lose it',
    leaveNo: 'Stay here',
  },

  auth: {
    title: 'Sign in to BAB',
    lede: "We'll email you a link. No password to remember, and none to get stolen.",
    emailLabel: 'Your email',
    emailPlaceholder: 'name@example.com',
    sendLink: 'Send me the link',
    sending: 'Sending…',
    sentTitle: 'Check your email',
    sentBody: "We've sent a link to **{email}**. Open it on this phone and you're in.",
    sentAgain: "Didn't arrive? Send it again",
    codeHint: "Link opening in the wrong place? The same email has a 6-digit code.",
    codeLabel: 'Code',
    codePlaceholder: '123456',
    codeSubmit: 'Go in',
    codeChecking: 'Checking…',
    codeWrong: 'Wrong or expired code. Send the email again and try once more.',
    or: 'or',
    google: 'Continue with Google',
    socialNote: "With Google, Google will know you use BAB. With the email link, it won't.",
    ageNote: "Google has a minimum age, so it might not work for you — which is completely fine. The email link always works.",
    trouble: 'Something went wrong',
    troubleBody: "We couldn't send the link. Check the address and try again — if it keeps happening, tell us.",
    signOut: 'Sign out',
  },

  hurt: {
    button: 'I got hurt',
    title: 'Something happened',
    lede: "You don't have to wait for a check-in. Tell me where, and what it feels like — that's enough to know what to do next.",
    whereStep: 'Where is it?',
    whatStep: 'What does it feel like?',
    whereFreeholder: 'Or type where — wrist, jaw, ribs…',
    close: 'Close',
  },

  bodymap: {
    sideLabel: 'Front or back',
    mirrorHint: 'Like a mirror: your left is on the left.',
    tapHint: 'Tap where you feel it.',
    chosen: 'You picked: {region}',
    onFront: "it's on the front",
    onBack: "it's on the back",
    legendMarked: 'already noted',
    legendHeat: 'how many times you marked it',
    legendFlag: 'worth showing someone',
    listOpen: 'Prefer a list?',
    listShort: 'List',
    listCloseShort: 'Figure',
    listClose: 'Back to the figure',
  },

  hydration: {
    title: 'One moment, setting up BAB',
    body: "I'm bringing what's already there onto this device. It only happens the first time you sign in here.",
    errorTitle: "I can't get your data back",
    errorBody: 'The network is only needed right now: from here on BAB works without signal too, and your check-ins save either way. Check your connection and try again.',
    retry: 'Try again',
  },

  settings: {
    title: 'You and your data',
    open: 'Your data and your account',
    back: 'Back',
    notSet: "You haven't said yet",
    dataTitle: 'Your data',
    dataHint: "Download them, and see what hasn't gone out yet",
    accountTitle: 'Your account',
    accountHint: 'Sign out of this phone, or delete everything',
    accountHintOffline: 'Delete everything',
    indexNote: "What you write in BAB is yours. From here you can take it with you whenever you like, and make it disappear whenever you like.",
    langNote: 'The choice travels with you: on a new phone BAB starts in this language already.',
    rhythmPrivacy: "Your cycle dates never appear in a card you share unless you tick the box yourself, every time.",

    agendaTitle: 'My week',
    agendaHelp: "It's how BAB knows which days to ask you for a check-in — and that the load was there even when you didn't write it down.",
    agendaNone: 'Nothing yet',
    agendaNoDays: 'No days picked. Saving like this removes these days from your week.',
    agendaNoEvents: 'Nothing coming up.',
    agendaEventsHelp: 'The dates that matter: BAB uses them to make sense of why a week went the way it did.',
    agendaEventsOne: 'One coming up',
    agendaEventsMany: '{n} coming up',
    agendaAddEvent: 'Add one',
    agendaEventName: 'What is it called (optional)',
    agendaKindLabel: 'What it is',
    agendaKindCompetition: 'Competition',
    agendaKindMatch: 'Match',
    agendaKindOther: 'Other',
    agendaPast: 'Already been',
    agendaPastNote: 'The ones already past stay: they explain why that week went the way it did.',
    agendaNote: 'Removing a day really deletes it, here and on the server. Your check-ins stay where they are.',

    profileTitle: 'Your profile',
    profileName: 'What we call you',
    profileSport: 'Your sport',
    profileBirth: 'Date of birth',
    profileSave: 'Save',
    profileSaving: 'Saving…',
    profileSaved: 'Saved.',
    profileQueued: 'Saved here. It goes out on its own as soon as there is a signal.',
    profileError: "I couldn't save that. Try again.",

    rhythmTitle: 'Your rhythm',
    profileCycleHint: "It has its own screen, kept apart — it's the most private thing we hold.",
    rhythmBody: 'You can change your mind whenever you like, either way.',
    rhythmContraception: 'Are you on the pill or another hormonal contraceptive?',

    langTitle: 'Language',

    signOutTitle: 'Sign out of BAB',
    signOutBody: 'Your data stays safe on the server: it comes back when you sign in again. It leaves this phone, so if someone else uses it they will not find your things.',
    signOutCta: 'Sign out',
    signOutWorking: 'Signing out…',
    signOutPendingOne: "Hold on: one thing hasn't gone out yet. If you leave now you lose it.",
    signOutPending: "Hold on: {n} things haven't gone out yet. If you leave now you lose them.",
    signOutAnywayOne: 'Sign out anyway and lose it',
    signOutAnyway: 'Sign out anyway and lose {n} things',
    signOutWait: "I'll wait",

    queueTitle: 'Waiting to go',
    queueBodyOne: 'One thing is saved here waiting for a signal. Nothing is lost.',
    queueBody: '{n} things are saved here waiting for a signal. Nothing is lost.',
    queueParkedOne: "One couldn't get through. It stays saved here and it's inside the file you download — if it doesn't clear up, tell us.",
    queueParked: "{n} couldn't get through. They stay saved here and they're inside the file you download — if it doesn't clear up, tell us.",

    exportTitle: 'Take your data with you',
    exportBody: "It's yours. You'll download a file with everything BAB holds about you: your check-ins, what you marked on the body map, your cycle dates, the consents you gave and when.",
    exportCta: 'Download everything',
    exportWorking: 'Preparing the file…',
    exportDone: "Done — it's in your downloads.",
    exportFromDevice: 'There was no signal, so the file holds what is on this device.',
    exportPendingOne: "One thing hadn't reached the server yet: it's in the file, at the end, marked as not yet sent.",
    exportPending: "{n} things hadn't reached the server yet: they're in the file, at the end, marked as not yet sent.",
    exportError: "I couldn't prepare the file. Try again in a moment.",

    deleteTitle: 'Delete your account',
    deleteBody: "Everything goes: your check-ins, what you felt, your cycle dates, your profile. It isn't archived somewhere — it's deleted, and we can't get it back.",
    deleteShared: "Anything you already sent someone — a body story, a message — stays with whoever received it: deleting here doesn't take it back.",
    deleteExportFirst: 'If you want to keep them, download them first.',
    deleteCta: 'I want to delete everything',
    deleteConfirm: 'Type {word} below to confirm.',
    deleteWord: 'DELETE',
    deleteGo: 'Delete forever',
    deleteAbort: 'Never mind',
    deleteWorking: 'Deleting…',
    deleteOffline: "The network is needed: I want to be sure it really goes from the server too, not just from this phone.",
    deleteError: "I couldn't delete it. Your data is still where it was — nothing happened halfway. Try again, or tell us.",
  },

  today: {
    greetingMorning: 'Morning, {name}',
    greetingEvening: 'Evening, {name}',
    greetingBack: 'Hey, good to see you',

    fresh: {
      title: 'Tune in before you go',
      body: 'Guess how today will feel, then check. About a minute.',
      cta: 'Start my tune-in',
      secondary: 'Not training today',
    },
    mid: {
      body: 'Your call this morning. Quality over quantity.',
      cta: 'Close the loop after training',
      secondary: 'Change my tempo',
      hint: "Come back a few minutes after you finish — that's when your signals are loudest.",
    },
    closed: {
      title: "That's today done",
      body: 'You read yourself, trained, and closed the loop. Nothing else to do here.',
      recapLabel: 'Today',
      predicted: 'Predicted',
      trained: 'Trained',
    },
    rest: {
      title: 'Rest day',
      body: "Nothing to do today. If you feel like it, one quick look at how you're recovering — that's all.",
      cta: 'A quick reflection',
      secondary: 'Skip — enjoy the day off',
      hint: 'Rest is where the training actually works. 🌿',
    },
    back: {
      title: 'Welcome back',
      body: "You've been away a bit — that's completely fine. Nothing is lost, and nothing resets. Let's just start from today.",
      cta: 'Tune in',
      hint: 'Your week mission is still waiting, exactly where you left it.',
    },
  },

  care: {
    bannerTitle: 'Your {region} is in Care',
    askedTold: 'Have you told an adult?',
    askedHow: 'How is it today?',
    stillTrain: 'You can still train around it — your tune-in will take it into account.',
  },

  checkin: {
    common: {
      next: 'Next',
      back: 'Back',
      skip: 'Skip',
      dontKnow: "I don't know",
      addThis: 'Add this',
      remove: 'Remove',
      reviewDifference: 'Review the difference',
      nothingYet: 'Nothing added yet — tap a spot to begin.',
      nothingHere: "Everything's quiet today",
      needChannels: "A channel or two is still missing. Go back and fill them in — without them the tempo can't be worked out.",
      andAnother: "There's another one",
      thatsAll: "That's all of them",
      peAsk: 'Did you have PE today?',
      peAskHelp: "It's easy to miss, and it changes the day's load quite a bit.",
    },
    pre: {
      title: 'Read your own signals',
      steps: ['Predict', 'Tune in', 'Compare', 'Adjust'],
      decodeLabel: 'Decode',
      predict: {
        label: 'Predict',
        title: "Before you tune in — what's your tempo today?",
        help: `Your "tempo" is just how much your body's got to give today. Take a guess now — you'll confirm it at the end. Guessing first trains your inner read, and being "wrong" isn't a fail, it's the whole point.`,
        confidence: 'How sure are you?',
        confidenceOptions: ['Just guessing', 'Fairly sure', 'Certain'],
        sleepHours: 'How much did you sleep?',
        sleepHoursOptions: ['Under 6h', '6–7h', '7–8h', '8–9h', 'Over 9h'],
      },
      tuneIn: {
        label: 'Tune in',
        title: 'Your channels',
        headspace: '🧠 Headspace',
        headspaceHelp: 'tap any that fit',
        headspaceOther: '➕ Other',
        headspaceOtherPlaceholder: 'In your own words…',
        surprise: 'Did anything surprise you?',
        surpriseOptions: ['No, as expected', 'A little', 'Quite a bit'],
        schoolLoad: "How's school right now?",
        schoolOptions: ['Chilled', 'Busy', 'Exam week'],
      },
      pinpoint: {
        label: 'Pinpoint & name it',
        title: 'Where do you feel it?',
        mapHint: 'As many as you notice, or none if all feels quiet.',
        help: `Pausing to find where a sensation sits, and putting a word to it, is the heart of the skill: it's how a vague "I feel off" becomes something you actually understand.`,
        front: 'Front',
        back: 'Back',
        allOver: 'All over',
        elsewhere: 'Somewhere else',
        where: 'Where',
        whatLike: 'What does it feel like?',
        showHints: 'What do these mean?',
        hideHints: 'Hide',
        howStrong: 'How strong is it?',
        whatDoes: 'And what does it do?',
      },
      result: {
        compareLabel: 'Compare — your read vs your body',
        planLabel: 'Adjust — your plan today',
        matched: 'You called it: **{tempo}**.',
        differed: 'You predicted **{predicted}**, your signals say **{suggested}**.',
        gapNote: "That gap is the most useful thing in the whole check-in — it's how you learn to read yourself. It isn't a mistake.",
        swapLabel: 'Your body, your call. Want to shift tempo?',
        copyForCoach: 'Copy what to tell your coach',
        again: 'New tune-in',
      },
    },
    post: {
      title: 'Close the loop',
      steps: ['Look back', 'Sense', 'Learn', 'Recover'],
      lookBack: {
        label: 'Look back',
        title: 'Which tempo did you actually train in today?',
        effort: 'How hard did it actually feel?',
        duration: 'How long was it?',
        durationOptions: ['Under 30 min', '30–60 min', '1–2 hours', 'Over 2 hours'],
        sessionType: 'What kind of session?',
        sessionTypeOptions: ['Training', 'Match or meet', 'PE', 'Gym', 'Other'],
      },
      senseLabel: 'Sense — a quick read',
      learnLabel: 'Learn',
      readSpot: 'This morning you predicted **{predicted}**, and that is exactly how it went.',
      readGap: 'This morning you predicted **{predicted}**, and you trained in **{actual}**.',
      readGapNote: "That gap isn't a mistake: it's the thing we're training. The more you notice it, the smaller it gets.",
      noPre: "I can't find this morning's check-in, so there's nothing to compare today. That's fine — what you write here still counts.",
      recapSignalsOne: 'You stopped and named one sensation. Doing that — finding where it sits and putting a word on it — is exactly the muscle we are training.',
      recapSignals: 'You stopped and named {n} sensations. Doing that — finding where it sits and giving it a word — is exactly the muscle we are training.',
      openQuestion: "A quiet question worth sitting with: what surprised you most about today — and which signal told you first?",
      notePlaceholder: 'Write it here if you like. Only you read this.',
      broughtHome: {
        title: 'What did you bring home?',
        help: 'Pick whatever sounds like you today — or none.',
      },
      communicate: {
        title: "Is there anything worth telling someone?",
        copy: 'Copy a line for your coach',
        notToday: 'Not today',
      },
      recoverLabel: "Recover — what your body's asking for now",
      bodySenseCta: 'Train your awareness',
      saving: 'Saving…',
      saved: "Saved. Even with no signal: it sends itself when you're back.",
    },
  },

  body: {
    title: 'My body',
    lede: 'Where your body spoke to you, and in what words.',
    windowLabel: 'How far back to look',
    windowOption: 'Last {n} days',
    pickHint: 'Tap a spot to see what you felt there.',
    heatNote: "The darker the area, the more times you marked it in this period.",
    emptyTitle: 'Nothing to read back yet',
    emptyBody: "Once you mark something on the map during a check-in, come back here: after a few days you start to see what keeps returning and what was just passing through.",
    quietTitle: 'Nothing in these {days} days',
    quietBody: "You haven't marked a single sensation. That's completely fine — there's nothing to catch up on.",
    topTitle: 'The spots that come back most',
    timesOne: 'once',
    times: '{n} times',
    lastToday: 'today',
    lastYesterday: 'yesterday',
    lastAgo: '{n} days ago',
    summaryOne: 'Once in {days} days, {when}.',
    summary: '{n} times in {days} days — the last one {when}.',
    flaggedOne: 'Once you marked it as worth showing someone.',
    flagged: '{n} times you marked it as worth showing someone.',
    wordsTitle: 'What you called it',
    entriesTitle: 'One by one',
    nothingHere: "You haven't marked anything here in this period.",
    undatedOne: 'One older signal has no date, so it stays out of this count.',
    undated: '{n} older signals have no date, so they stay out of this count.',
  },

  diag: {
    title: 'How the app is doing',
    open: "Something not saving?",
    lede: "If it looks like something isn't being saved, here's what's actually going on. You can copy it and send it to us: it contains nothing you wrote.",
    serverTitle: 'The server',
    serverOn: 'Connected.',
    serverOff: "Not connected. BAB keeps working and saves everything here, but nothing goes out.",
    sessionOn: "You're signed in.",
    sessionOff: "You're not signed in: what you write stays on this device.",
    storageTitle: 'Storage on this device',
    storageOn: 'Working.',
    storageOff: "I can't read it. That happens in private browsing, or if you've run out of space.",
    storageCount: '{n} things saved here.',
    queueTitle: 'Waiting to go',
    queueNone: 'Nothing waiting: it has all arrived.',
    queueWaitingOne: 'One thing is waiting for a signal.',
    queueWaiting: '{n} things are waiting for a signal.',
    queueStuckOne: "One couldn't get through.",
    queueStuck: "{n} couldn't get through.",
    push: 'Try sending now',
    pushing: 'Trying…',
    pushDone: '{n} went out. {left} left.',
    copy: 'Copy the report',
    copied: 'Copied.',
    dontWipe: "Don't delete the app or your browser data while something is still waiting: what hasn't gone out only exists here.",
  },

  rhythm: {
    title: 'My rhythm',
    rightNow: "Right now you're in",
    aroundDay: 'around day {n} of your cycle',
    mapNotTimetable: "It's a map, not a timetable. 🗺️",
    updateDates: 'Update my dates',
    turnOff: 'Turn this off',
    learnPhases: 'What the four phases can feel like',
    uncertainOne: "You've given BAB **one date** so far, so this is a rough guess. Add another one or two and it gets a lot better.",
    uncertainVariable: 'Your last cycles were **{spread} days apart** at their widest — completely normal at your age, and it means this is a loose read rather than a precise one.',
    uncertainOk: "Based on the **{n} dates** you gave, your cycle runs around **{len} days**. It'll keep shifting — that's normal while it settles.",
    staleTitle: "It's been a while",
    staleBody: "Your last date was more than a full cycle ago, so BAB won't guess where you are — guessing would just be making something up. Pop in your latest date and the map comes back.",
    staleCta: 'Add my latest date',
    notYetTitle: "Nothing to track yet — and that's completely normal",
    notYetBody: 'Bodies begin on their own timeline, anywhere across these years. When yours starts, you can switch this on and BAB will start mapping your rhythm.',
    notYetCta: "I've started — set it up",
    offTitle: 'This part is switched off',
    offBody: 'You chose not to share your cycle, and everything else in BAB works exactly the same. You can switch it on any time in Settings — no rush, and no reminders from us.',
  },

  me: {
    title: 'Me',
    readingTitle: 'Your read keeps getting sharper',
    readingLabel: 'How well you read yourself',
    collectingTitle: "Still learning how you're built",
    collectingBody: 'Every check-in is a dot. Once there are enough of them, the dots start showing patterns that are yours alone.',
    collectingCount: '{done} of {total} closed days',
    collectingLeftOne: 'One more and your read starts to show.',
    collectingLeft: '{n} more and your read starts to show.',
    readingDown: "Your gap is getting smaller. You're learning to feel it before you check it.",
    readingFlat: "Your gap is holding steady. That's fine: reading yourself doesn't improve in a straight line.",
    readingUp: "Your guesses have been further off lately. It happens, and it usually means something changed — not that you're doing worse.",
    readingNoAxis: "No numbers: it's the shape that matters, not a score.",
    daysTitle: 'My days',
    daysHelp: "The last four weeks. The days you didn't check in are here too — because those are information as well, and hiding them would be kinder but less true.",
    dayBoth: 'loop closed',
    dayHalf: 'before only',
    dayNone: 'nothing',
    insightCaveat: "These are ideas, not facts. You're the expert on you: keep the ones that feel true, and question the ones that don't.",
    insightYes: 'That sounds like me',
    insightNo: "Doesn't fit",
    bodyTitle: 'My body',
    bodyBody: "What you marked on the map, put back together: which spots return, and what words you gave them.",
    bodyCta: 'Look at the map',
    storyTitle: 'Your weekly story',
    storyBody: 'Something you can hand to a coach or a parent',
    storyCta: 'Put one together',
    storyLocked: 'Unlocks after your first full week',
  },

  story: {
    title: 'My week',
    chooseTitle: 'What goes in?',
    chooseHelp: 'Nothing is shared until you say so. Tap to add or remove — the card below updates as you go.',
    blocks: {
      tempos: 'My tempos',
      temposHelp: 'Which gear you trained in each day',
      spots: 'Where I felt things',
      spotsHelp: 'The spots that came up most, and what they felt like',
      energy: 'My energy through the week',
      energyHelp: 'A simple line — no numbers, no score',
      note: 'What I wrote',
      noteHelp: 'The note you left after training',
      cycle: 'My cycle',
      cycleHelp: 'Which phase you were in — off unless you turn it on',
    },
    cycleNote: 'Your cycle never goes into a card on its own, and turning it on here applies to **this card only** — never to the next one. Your staff can see the dates from your check-ins anyway: this tick is only about what *you* send, and to whom.',
    previewTitle: "This is exactly what they'll see",
    previewHelp: 'What you send is a picture, not access. Whoever gets it sees exactly this — no link to follow, nothing else to go and look at.',
    send: 'Send this',
    keep: 'Keep it for me',
    saidTitle: "And here's how to open the conversation",
    saidHelp: 'Copy this if it helps — or say it your own way, which is better.',
    copyWords: 'Copy these words',
    copied: 'Copied ✓',
    stuckTitle: "Not sure how to start?",
    stuckPhrases: [
      "I'd like to show you something about how I'm doing this week.",
      "I noticed something in my body and wanted to tell you before it becomes an issue.",
      "I need to talk to you about how I'm feeling — got two minutes after training?",
    ],
    saved: 'Saved',
    download: 'Save the picture',
    emptyState: "Nothing selected yet — pick at least one thing above, and it'll appear here.",
  },

  heart: {
    conceptTitle: 'Guess. Then really feel.',
    conceptHelp: "It's one little loop, and you'll do it every day:",
    step1Title: 'Guess first',
    step1Body: "Take a quick guess about your body, before you check. Locking a guess in is what makes it count.",
    step2Title: 'Then really feel',
    step2Body: "Slow down and actually sense what's going on, bit by bit.",
    step3Title: 'Learn the gap',
    step3Body: "The space between your guess and your body is where you get sharper — being off isn't a fail, it's the whole point.",
    conceptFooter: "Do that enough times and your guesses get scary-good. That's you, learning to trust yourself.",

    settleTitle: 'Can you feel your own heartbeat?',
    settleBody: "Sit still and quiet for a moment. Don't touch anything yet — see if you can feel your heart beating, maybe in your chest, your neck, even your ears.",
    settleNote: "Some days it's easy to feel, some days it's faint. Either is fine — you're just tuning in.",

    guessTitle: 'How fast is it going?',
    guessHelp: "No checking yet — just your gut. Right now, your heart feels…",
    slow: 'Slow',
    slowHelp: 'calm & settled',
    medium: 'Medium',
    mediumHelp: 'ticking along',
    fast: 'Fast',
    fastHelp: 'up & going',
    guessFooter: "Locking in a guess is what turns this into training — pick the one that feels closest.",

    countTitle: "Now let's count it.",
    countHelp: 'Put two fingers on the side of your neck, or the inside of your wrist, until you feel the beat. When you start, tap the circle once for every beat you feel, for 15 seconds.',
    tapStart: 'Start',
    tapReady: 'tap to begin',
    tapAriaLabel: 'Tap the circle on every beat',
    tapGo: 'TAP',
    tapGoSub: 'every beat',
    tapCounting: 'Counting…',
    tapDone: 'Done! You felt',
    tapBeatsCounted: 'Beats counted',
    tapBeats: 'beats',

    revealMatchTitle: 'Nice read! 🎯',
    revealMissTitle: 'Interesting — a little off.',
    bpmLabel: 'beats per minute (you counted)',
    yourGuess: 'Your guess',
    youCounted: 'You counted',
    revealMatchNote: "Your guess matched what you counted. That means you're already picking up a real signal from inside — **hold onto how that felt**, it's your reference point.",
    revealMissNote: "Your guess and your count landed in different bands. That's **completely normal on day one**, and it's exactly the gap you'll get better at closing. You just found your starting point.",
    revealFooter: "That feeling — sensing something inside you, then checking it — is called interoception. It's a muscle, and you just did your first rep.",

    wrapTitle: 'This is the whole game.',
    wrapBody: "You'll run that same loop — guess, feel, learn the gap — in two quick moments each training day:",
    checkinTitle: 'Check-in',
    checkinBody: 'In the 30 minutes before training — guess your day, then tune in.',
    checkoutTitle: 'Check-out',
    checkoutBody: 'In the 30 minutes after — see how it actually went.',
    gearsIntro: 'Both help you find your gear for the day:',
    wrapNote: "Your gear is just how much your body's got to give today. No gear is good or bad — you notice it and honour it.",
  },

  bodySense: {
    entryTitle: 'Quick reps',
    entryBody: 'Guess → feel → check. 60-90 seconds to train how well you read yourself.',
    entryCta: 'Try one',
    title: 'Quick reps',
    lead: "Little guess → feel → check exercises, 60-90 seconds each. No wearable, no scores — just your body, your hands, and your attention. Do one anytime.",
    filterAll: 'All',
    close: 'Close',
    next: 'Next →',
    finish: 'Finish ✓',
    finishToast: "Nice rep 🌱 — that's your inner read getting sharper.",
    heartbeatName: 'Heartbeat',
    heartbeatTrains: 'Accuracy',
    heartbeatDur: '60s',
    scaleLowShort: 'low',
    scaleHighShort: 'high',
    twosidesMatch: 'Spot on.',
    twosidesMiss: 'Surprise — and useful.',
    twosidesMatchNote: "You could feel the difference between your two sides before testing — that's a sharp read.",
    twosidesMissNote: "Bodies aren't always even, and the tight side is easy to miss. Noticing it early keeps you ahead of little niggles.",
    twosidesYourGuess: 'Your guess',
    twosidesActual: 'Actually',
    zoneBefore: 'Before',
    zoneAfter: 'After',
    zoneSame: 'Your dial held steady.',
    zoneDown: 'Your dial came down {n} {unit}.',
    zoneUp: 'Your dial lifted {n} {unit}.',
    zoneNotchOne: 'notch',
    zoneNotch: 'notches',
    zoneNote: "The point isn't the number — it's that you can move it on purpose. Before a match, aim for your best zone: alert and ready, not flat, not jittery.",
  },

  onboarding: {
    welcomeTitle: 'This is about learning to read yourself',
    welcomeBody: 'Most sports apps measure you from the outside and tell you what to do. BAB does the opposite: it helps you learn what your own body is telling you — so you know when to push, when to rest, and how to say it out loud.',
    back: 'Back',
    consentAthlete: "I've read it and I'm in",
    consentGuardian: 'A parent or guardian has read it and is in',
    consentVersion: 'v1-draft',
    consentDraftWarning: 'This text is a placeholder: the real one lands before the app is used for real.',
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    timeLabel: 'What time, usually',
    eventDateLabel: 'Your next meet, if you already know it',
    letsGo: "Let's go",
    continue: 'Continue',
    consentTitle: 'Before anything else',
    consentHelp: "You're under 18, so we need two yeses — yours and a parent's or guardian's. Read them together if you can.",

    nameTitle: 'What should we call you?',
    nameHelp: 'The name you want to see when you open the app. You can change it any time.',
    namePlaceholder: 'Your name',
    birthdayTitle: 'When’s your birthday?',
    birthdayHelp: "Two reasons: so we can wish you a happy one, and so we know which questions make sense to ask you and which don't.",
    sportTitle: 'What sport do you do?',
    sportHelp: 'You can add more than one. It changes the words BAB uses with you — meets or matches, and what counts as a session.',
    sportLabel: 'Your sport',
    sportOtherPlaceholder: 'Type your sport',
    setUpLater: "I'll set this up later",

    weekTraining: 'Training',
    weekTrainingHelp: 'Pick the days and the time. You can always change them later.',
    trainDayTitle: 'When do you train {sport}?',
    trainStartTitle: 'What time do you usually start?',
    trainEndTitle: 'And what time do you usually finish?',
    trainEndHelp: "Just a rough guess is fine — you can fix it any time",
    weekPe: 'PE at school',
    weekPeHelp: "It counts as load even when it doesn't feel like it",
    weekEvents: 'Meets and matches',
    weekEventsHelp: "Don't know the time yet? That's fine — add it later",

    whoSeesTitle: 'Who sees what',
    whoSeesTeam: 'Your staff can see your check-ins: your tempos, your channels, where you feel things, and your cycle dates. It helps them coach you better, and saves you having to say it all out loud.',
    whoSeesPrivate: 'What you write in your own words stays yours. Nobody else reads the notes you leave after training.',
    whoSeesYou: 'And the data is yours: take all of it with you, or delete all of it, any time, from Settings.',
    rhythmTitle: 'Do you have your period yet?',
    rhythmBody: 'If you do, BAB can use it as the backdrop behind all your other signals — the thing almost no sports app does. You can switch it off any time, and before you decide we tell you exactly who sees it.',
    rhythmYes: 'Yes, I have it',
    rhythmYesHelp: 'BAB will map your phases from the dates you give it',
    firstPeriodAgeTitle: 'If you remember, how old were you when you first got your period?',
    firstPeriodAgeHelp: "Only if you know — it's fine if you don't remember.",
    firstPeriodAgePlaceholder: 'Age',
    rhythmNotYet: 'Not yet',
    rhythmSkip: "I'd rather not say",
    datesTitle: 'When was your last period?',
    datesHelp: 'Tap every day you bled. A best guess is fine.',
    datesPrevTitle: 'And before that, roughly when?',
    datesPrevHelp: 'Just the day it started — a best guess is fine.',
    datesBeforeTitle: 'And before that one?',
    datesBeforeHelp: 'Last one, promise.',
    datesSkip: "I don't remember",
    contraceptionTitle: 'Are you on any hormonal contraception?',
    contraceptionHelp: 'Hormonal contraception can affect the signals your body sends you. That\'s why it\'s worth noting.',
    contraceptionUndisclosed: 'I\'d rather not say',
    cyclePrivacy: "**Your staff can see your cycle dates**, not what you write. You can switch it off any time.",
    doneTitle: "That's it, {name}",
    doneBody: 'Here\'s what BAB knows about you. You can change any of it later, in Settings.',
    doneLastCycle: 'Last cycle',
    doneCycleYearsOne: 'Had her period for about {n} year',
    doneCycleYears: 'Had her period for about {n} years',
    doneCta: 'Start my first tune-in',
  },

  coach: {
    title: 'The team',
    subtitle: 'Today, at a glance',
    notConnected: 'The dashboard needs a connection: it reads the whole team from the server, not from this device.',
    noTeams: "This account isn't linked to a team. If it should be, tell us.",
    redFlagsTitle: '🚩 Worth looking at now',
    redFlagsHelp: "Open flags, oldest first. They don't wait for the next session.",
    redFlagsNone: 'No open flags.',
    toldAdult: 'told an adult',
    notToldAdult: 'no record of telling anyone',
    openedToday: 'today',
    openedDay: 'a day ago',
    openedDays: '{n} days ago',
    rosterTitle: "Who's here",
    checkedInNo: 'no check-in today',
    onlyPre: 'before only',
    predicted: 'predicted',
    trained: 'trained',
    effort: 'effort',
    peYes: 'PE ✓',
    peNo: 'PE ✗',
    back: '← The team',
    historyTitle: 'The last two weeks',
    cycleTitle: 'Cycle dates',
    cycleNote: "These are the dates she entered, not a forecast. At her age cycles are often still irregular: use them as context for a day, never to plan around, and never as a topic unless she opens it.",
    cycleNone: 'No dates entered.',
    nothingYet: 'No check-ins yet.',
  },

  common: {
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    offline: "You're offline — what you write is saved here and sends itself later.",
    loading: 'One moment…',
  },

  disclaimer:
    "BAB helps you understand yourself — it doesn't replace your coach, a physio or a doctor, who can see and check things a screen can't. If anything ever feels wrong with your body or your mind, tell a trusted adult. That's always the strong move.",
}
