import type { Copy } from './index'

/**
 * English UI copy. Must conform to `Copy` — a missing key is a compile error.
 * Most of this is lifted verbatim from the v3 prototypes, which is where the
 * tone was worked out; don't "improve" it without a reason.
 */
export const en: Copy = {
  app: {
    name: 'BAB',
    tagline: 'Learn to read your own signals',
  },

  tabs: {
    today: 'Today',
    journey: 'Journey',
    me: 'Me',
    ariaLabel: 'Main navigation',
  },

  auth: {
    title: 'Sign in to BAB',
    lede: "We'll email you a link. No password to remember, and none to get stolen.",
    emailLabel: 'Your email',
    emailPlaceholder: 'name@example.com',
    sendLink: 'Send me the link',
    sending: 'Sending…',
    sentTitle: 'Check your email',
    sentBody: "We've sent a link to **{email}**. Open it on this phone and you're in.",
    sentAgain: "Didn't arrive? Send it again",
    or: 'or',
    google: 'Continue with Google',
    socialNote: "With Google, Google will know you use BAB. With the email link, it won't.",
    ageNote: "Google has a minimum age, so it might not work for you — which is completely fine. The email link always works.",
    trouble: 'Something went wrong',
    troubleBody: "We couldn't send the link. Check the address and try again — if it keeps happening, tell us.",
    signOut: 'Sign out',
  },

  hurt: {
    button: 'I got hurt',
    title: 'Something happened',
    lede: "You don't have to wait for a check-in. Tell me where, and what it feels like — that's enough to know what to do next.",
    whereStep: 'Where is it?',
    whatStep: 'What does it feel like?',
    whereFreeholder: 'Or type where — wrist, jaw, ribs…',
    close: 'Close',
  },

  today: {
    greetingMorning: 'Morning, {name}',
    greetingEvening: 'Evening, {name}',
    greetingBack: 'Hey, good to see you',

    fresh: {
      title: 'Tune in before you go',
      body: 'Guess how today will feel, then check. About a minute.',
      cta: 'Start my tune-in',
      secondary: 'Not training today',
    },
    mid: {
      body: 'Your call this morning. Quality over quantity.',
      cta: 'Close the loop after training',
      secondary: 'Change my tempo',
      hint: "Come back a few minutes after you finish — that's when your signals are loudest.",
    },
    closed: {
      title: "That's today done",
      body: 'You read yourself, trained, and closed the loop. Nothing else to do here.',
      recapLabel: 'Today',
      predicted: 'Predicted',
      trained: 'Trained',
    },
    rest: {
      title: 'Rest day',
      body: "Nothing to do today. If you feel like it, one quick look at how you're recovering — that's all.",
      cta: 'A quick reflection',
      secondary: 'Skip — enjoy the day off',
      hint: 'Rest is where the training actually works. 🌿',
    },
    back: {
      title: 'Welcome back',
      body: "You've been away a bit — that's completely fine. Nothing is lost, and nothing resets. Let's just start from today.",
      cta: 'Tune in',
      hint: 'Your week mission is still waiting, exactly where you left it.',
    },
  },

  care: {
    bannerTitle: 'Your {region} is in Care',
    askedTold: 'Have you told an adult?',
    askedHow: 'How is it today?',
    stillTrain: 'You can still train around it — your tune-in will take it into account.',
  },

  checkin: {
    common: {
      next: 'Next',
      back: 'Back',
      skip: 'Skip',
      dontKnow: "I don't know",
      addThis: 'Add this',
      remove: 'Remove',
      reviewDifference: 'Review the difference',
      nothingYet: 'Nothing added yet — tap a spot to begin.',
      peAsk: 'Did you have PE today?',
      peAskHelp: "It's easy to miss, and it changes the day's load quite a bit.",
    },
    pre: {
      title: 'Read your own signals',
      steps: ['Predict', 'Tune in', 'Compare', 'Adjust'],
      predict: {
        label: 'Step 1 · Predict',
        title: "Before you tune in — what's your tempo today?",
        help: `Your "tempo" is just how much your body's got to give today. Take a guess now — you'll confirm it at the end. Guessing first trains your inner read, and being "wrong" isn't a fail, it's the whole point.`,
        confidence: 'How sure are you?',
        confidenceOptions: ['Just guessing', 'Fairly sure', 'Certain'],
        sleepHours: 'How much did you sleep?',
        sleepHoursOptions: ['Under 6h', '6–7h', '7–8h', '8–9h', 'Over 9h'],
      },
      tuneIn: {
        label: 'Step 2 · Tune in',
        title: 'Your channels',
        headspace: '🧠 Headspace',
        headspaceHelp: 'tap any that fit',
        surprise: 'Did anything surprise you?',
        surpriseOptions: ['No, as expected', 'A little', 'Quite a bit'],
        schoolLoad: "How's school right now?",
        schoolOptions: ['Chilled', 'Busy', 'Exam week'],
      },
      pinpoint: {
        label: 'Step 2 · Pinpoint & name it',
        title: 'Where do you feel it? Give it a name.',
        help: `Pausing to find where a sensation sits, and putting a word to it, is the heart of the skill — it's how a vague "I feel off" becomes something you actually understand. Tap a spot, flip between front and back, then choose what it feels like. Add as many as you notice, or none if all feels quiet.`,
        front: 'Front',
        back: 'Back',
        allOver: 'All over',
        elsewhere: 'Somewhere else',
        where: 'Where',
        whatLike: 'What does it feel like?',
        howStrong: 'How strong is it?',
        whatDoes: 'And what does it do?',
      },
      result: {
        compareLabel: 'Step 3 · Compare — your read vs your body',
        planLabel: 'Step 4 · Adjust — your plan today',
        matched: 'You called it: **{tempo}**.',
        differed: 'You predicted **{predicted}**, your signals say **{suggested}**.',
        gapNote: "That gap is the most useful thing in the whole check-in — it's how you learn to read yourself. It isn't a mistake.",
        swapLabel: 'Your body, your call. Want to shift tempo?',
        copyForCoach: 'Copy what to tell your coach',
        again: 'New tune-in',
      },
    },
    post: {
      title: 'Close the loop',
      steps: ['Look back', 'Sense', 'Learn', 'Recover'],
      lookBack: {
        label: 'Step 1 · Look back',
        title: 'Which tempo did you actually train in today?',
        effort: 'How hard did it actually feel?',
        duration: 'How long was it?',
        durationOptions: ['Under 30 min', '30–60 min', '1–2 hours', 'Over 2 hours'],
        sessionType: 'What kind of session?',
        sessionTypeOptions: ['Training', 'Match or meet', 'PE', 'Gym', 'Other'],
      },
      senseLabel: 'Step 2 · Sense — a quick read',
      learnLabel: 'Step 3 · Learn',
      readSpot: 'This morning you predicted **{predicted}**, and that is exactly how it went.',
      readGap: 'This morning you predicted **{predicted}**, and you trained in **{actual}**.',
      readGapNote: "That gap isn't a mistake: it's the thing we're training. The more you notice it, the smaller it gets.",
      noPre: "I can't find this morning's check-in, so there's nothing to compare today. That's fine — what you write here still counts.",
      recapSignals: 'You stopped and named {n} sensations. Doing that — finding where it sits and giving it a word — is exactly the muscle we are training.',
      openQuestion: "A quiet question worth sitting with: what surprised you most about today — and which signal told you first?",
      notePlaceholder: 'Write it here if you like. Only you read this.',
      broughtHome: {
        title: 'What did you bring home?',
        help: 'Pick whatever sounds like you today — or none.',
      },
      communicate: {
        title: "Is there anything worth telling someone?",
        copy: 'Copy a line for your coach',
        notToday: 'Not today',
      },
      recoverLabel: "Step 4 · Recover — what your body's asking for now",
      saving: 'Saving…',
      saved: "Saved. Even with no signal: it sends itself when you're back.",
    },
  },

  rhythm: {
    title: 'My rhythm',
    rightNow: "Right now you're in",
    aroundDay: 'around day {n} of your cycle',
    mapNotTimetable: "It's a map, not a timetable. 🗺️",
    updateDates: 'Update my dates',
    turnOff: 'Turn this off',
    learnPhases: 'What the four phases can feel like',
    uncertainOne: "You've given BAB **one date** so far, so this is a rough guess. Add another one or two and it gets a lot better.",
    uncertainVariable: 'Your last cycles were **{spread} days apart** at their widest — completely normal at your age, and it means this is a loose read rather than a precise one.',
    uncertainOk: "Based on the **{n} dates** you gave, your cycle runs around **{len} days**. It'll keep shifting — that's normal while it settles.",
    staleTitle: "It's been a while",
    staleBody: "Your last date was more than a full cycle ago, so BAB won't guess where you are — guessing would just be making something up. Pop in your latest date and the map comes back.",
    staleCta: 'Add my latest date',
    notYetTitle: "Nothing to track yet — and that's completely normal",
    notYetBody: 'Bodies begin on their own timeline, anywhere across these years. When yours starts, you can switch this on and BAB will start mapping your rhythm.',
    notYetCta: "I've started — set it up",
    offTitle: 'This part is switched off',
    offBody: 'You chose not to share your cycle, and everything else in BAB works exactly the same. You can switch it on any time in Settings — no rush, and no reminders from us.',
  },

  me: {
    title: 'Me',
    readingTitle: 'Your read keeps getting sharper',
    readingLabel: 'How well you read yourself',
    collectingTitle: "Still learning how you're built",
    collectingBody: 'Every check-in is a dot. Once there are enough of them, the dots start showing patterns that are yours alone.',
    collectingCount: '{done} of {total} check-ins',
    collectingLeft: 'About {n} more and the first patterns start to appear.',
    insightCaveat: "These are ideas, not facts. You're the expert on you: keep the ones that feel true, and question the ones that don't.",
    insightYes: 'That sounds like me',
    insightNo: "Doesn't fit",
    storyTitle: 'Your weekly story',
    storyBody: 'Something you can hand to a coach or a parent',
    storyCta: 'Put one together',
    storyLocked: 'Unlocks after your first full week',
  },

  story: {
    title: 'My week',
    chooseTitle: 'What goes in?',
    chooseHelp: 'Nothing is shared until you say so. Tap to add or remove — the card below updates as you go.',
    blocks: {
      tempos: 'My tempos',
      temposHelp: 'Which gear you trained in each day',
      spots: 'Where I felt things',
      spotsHelp: 'The spots that came up most, and what they felt like',
      energy: 'My energy through the week',
      energyHelp: 'A simple line — no numbers, no score',
      note: 'What I wrote',
      noteHelp: 'The note you left after training',
      cycle: 'My cycle',
      cycleHelp: 'Which phase you were in — off unless you turn it on',
    },
    cycleNote: 'Your cycle never goes into a card on its own, and turning it on here applies to **this card only** — never to the next one. Your staff can see the dates from your check-ins anyway: this tick is only about what *you* send, and to whom.',
    previewTitle: "This is exactly what they'll see",
    previewHelp: 'What you send is a picture, not access. Whoever gets it sees exactly this — no link to follow, nothing else to go and look at.',
    send: 'Send this',
    keep: 'Keep it for me',
    saidTitle: "And here's how to open the conversation",
    saidHelp: 'Copy this if it helps — or say it your own way, which is better.',
    copyWords: 'Copy these words',
    emptyState: "Nothing selected yet — pick at least one thing above, and it'll appear here.",
  },

  onboarding: {
    welcomeTitle: 'This is about learning to read yourself',
    welcomeBody: 'Most sports apps measure you from the outside and tell you what to do. BAB does the opposite: it helps you learn what your own body is telling you — so you know when to push, when to rest, and how to say it out loud.',
    isTitle: 'What this is',
    isItems: [
      'A way to understand what your body is telling you',
      'A place where "I\'m going easy today" is a right answer',
      'The words to say it to whoever coaches you',
    ],
    isNotTitle: "What this isn't",
    isNotItems: [
      'A grade on your day',
      'A way to compare yourself with others',
      'Anything to do with food or weight',
    ],
    back: 'Back',
    consentAthlete: "I've read it and I'm in",
    consentGuardian: 'A parent or guardian has read it and is in',
    consentVersion: 'v1-draft',
    consentDraftWarning: 'This text is a placeholder: the real one lands before the app is used for real.',
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    timeLabel: 'What time, usually',
    eventDateLabel: 'Your next meet, if you already know it',
    letsGo: "Let's go",
    continue: 'Continue',
    consentTitle: 'Before anything else',
    consentHelp: "You're under 18, so we need two yeses — yours and a parent's or guardian's. Read them together if you can.",

    nameTitle: 'What should we call you?',
    nameHelp: 'The name you want to see when you open the app. You can change it any time.',
    namePlaceholder: 'Your name',
    birthdayTitle: 'When’s your birthday?',
    birthdayHelp: "Two reasons: so we can wish you a happy one, and so we know which questions make sense to ask you and which don't.",
    sportTitle: 'What sport do you do?',
    sportHelp: 'It changes the words BAB uses with you — meets or matches, and what counts as a session.',
    sportLabel: 'Your sport',
    setUpLater: "I'll set this up later",

    weekTitle: 'My week',
    weekHelp: 'Mark when you train, when you have PE, and any fixtures you already know. That way BAB knows when to expect you — and stays quiet the rest of the time.',
    weekTraining: 'Training',
    weekTrainingHelp: 'Days and times, so it knows when to ask for your before and after',
    weekPe: 'PE at school',
    weekPeHelp: "It counts as load even when it doesn't feel like it",
    weekEvents: 'Meets and matches',
    weekEventsHelp: "Don't know the time yet? That's fine — add it later",

    whoSeesTitle: 'Who sees what',
    whoSeesTeam: 'Your staff can see your check-ins: your tempos, your channels, where you feel things, and your cycle dates. It helps them coach you better, and saves you having to say it all out loud.',
    whoSeesPrivate: 'What you write in your own words stays yours. Nobody else reads the notes you leave after training.',
    whoSeesYou: 'And the data is yours: take all of it with you, or delete all of it, any time, from Settings.',
    rhythmTitle: 'Do you have your period yet?',
    rhythmBody: 'If you do, BAB can use it as the backdrop behind all your other signals — the thing almost no sports app does. You can switch it off any time, and before you decide we tell you exactly who sees it.',
    rhythmYes: 'Yes, I have it',
    rhythmYesHelp: 'BAB will map your phases from the dates you give it',
    rhythmNotYet: 'Not yet',
    rhythmNotYetHelp: 'Completely normal — bodies start on their own timeline, anywhere across these years',
    rhythmSkip: "I'd rather not say",
    rhythmSkipHelp: 'Fine too. Everything else works exactly the same',
    datesTitle: 'When did your last periods start?',
    datesHelp: 'Best guess is fine. Even one date lets BAB start; two or three make it better. At your age cycles are often still settling, so BAB treats this as a rough map, never a schedule.',
    dateMostRecent: 'Most recent',
    datePrevious: 'The one before',
    dateBefore: 'And before that',
    contraceptionTitle: 'Are you on any hormonal contraception?',
    contraceptionHelp: 'Pill, implant, coil, patch, injection. About half of athletes are, and it changes what your signals mean — so BAB needs to know to read them properly.',
    whyDatesTitle: `Why BAB asks for dates instead of "which phase are you in?"`,
    whyDatesBody: "Because working it out from dates is the reliable way — guessing your own phase isn't, especially in the first years. You'll never have to classify yourself.",
    cyclePrivacy: "This is the most sensitive thing we ask you for, so here it is straight: **your staff can see your cycle dates**, along with the rest of your check-ins. They can't see what you write. And if you'd rather they didn't, this part switches off any time — the rest of BAB works exactly the same.",
    doneTitle: "That's it",
    doneBody: 'Here\'s what BAB knows about you. You can change any of it later, in Settings.',
    doneCta: 'Start my first tune-in',
  },

  settings: {
    title: 'Settings',
    profile: 'Profile',
    rhythm: 'My rhythm',
    privacy: 'Privacy and data',
    notifications: 'Reminders',
    help: 'Help',
    exportData: 'Export my data',
    deleteAccount: 'Delete my account',
    deleteConfirm: 'Really delete everything? There is no going back.',
    language: 'Language',
  },

  common: {
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    offline: "You're offline — what you write is saved here and sends itself later.",
    loading: 'One moment…',
  },

  disclaimer:
    "BAB helps you understand yourself — it doesn't replace your coach, a physio or a doctor, who can see and check things a screen can't. If anything ever feels wrong with your body or your mind, tell a trusted adult. That's always the strong move.",
}
