import type { Copy } from './index'

/**
 * English UI copy. Must conform to `Copy` — a missing key is a compile error.
 * Most of this is lifted verbatim from the v3 prototypes, which is where the
 * tone was worked out; don't "improve" it without a reason.
 */
export const en: Copy = {
  app: {
    name: 'BAB',
    tagline: 'Learn to read your own signals',
  },

  tabs: {
    today: 'Today',
    journey: 'Journey',
    me: 'Me',
    ariaLabel: 'Main navigation',
  },

  hurt: {
    button: 'I got hurt',
    title: 'Something happened',
    lede: "You don't have to wait for a check-in. Tell me where, and what it feels like — that's enough to know what to do next.",
    whereStep: 'Where is it?',
    whatStep: 'What does it feel like?',
    whereFreeholder: 'Or type where — wrist, jaw, ribs…',
    close: 'Close',
  },

  today: {
    greetingMorning: 'Morning, {name}',
    greetingEvening: 'Evening, {name}',
    greetingBack: 'Hey, good to see you',

    fresh: {
      title: 'Tune in before you go',
      body: 'Guess how today will feel, then check. About a minute.',
      cta: 'Start my tune-in',
      secondary: 'Not training today',
    },
    mid: {
      body: 'Your call this morning. Quality over quantity.',
      cta: 'Close the loop after training',
      secondary: 'Change my tempo',
      hint: "Come back a few minutes after you finish — that's when your signals are loudest.",
    },
    closed: {
      title: "That's today done",
      body: 'You read yourself, trained, and closed the loop. Nothing else to do here.',
      recapLabel: 'Today',
      predicted: 'Predicted',
      trained: 'Trained',
    },
    rest: {
      title: 'Rest day',
      body: "Nothing to do today. If you feel like it, one quick look at how you're recovering — that's all.",
      cta: 'A quick reflection',
      secondary: 'Skip — enjoy the day off',
      hint: 'Rest is where the training actually works. 🌿',
    },
    back: {
      title: 'Welcome back',
      body: "You've been away a bit — that's completely fine. Nothing is lost, and nothing resets. Let's just start from today.",
      cta: 'Tune in',
      hint: 'Your week mission is still waiting, exactly where you left it.',
    },
  },

  care: {
    bannerTitle: 'Your {region} is in Care',
    askedTold: 'Have you told an adult?',
    askedHow: 'How is it today?',
    stillTrain: 'You can still train around it — your tune-in will take it into account.',
  },

  checkin: {
    common: {
      next: 'Next',
      back: 'Back',
      skip: 'Skip',
      dontKnow: "I don't know",
      addThis: 'Add this',
      remove: 'Remove',
      reviewDifference: 'Review the difference',
      nothingYet: 'Nothing added yet — tap a spot to begin.',
    },
    pre: {
      title: 'Read your own signals',
      steps: ['Predict', 'Tune in', 'Compare', 'Adjust'],
      predict: {
        label: 'Step 1 · Predict',
        title: "Before you tune in — what's your tempo today?",
        help: `Your "tempo" is just how much your body's got to give today. Take a guess now — you'll confirm it at the end. Guessing first trains your inner read, and being "wrong" isn't a fail, it's the whole point.`,
        confidence: 'How sure are you?',
        confidenceOptions: ['Just guessing', 'Fairly sure', 'Certain'],
        sleepHours: 'How much did you sleep?',
      },
      tuneIn: {
        label: 'Step 2 · Tune in',
        title: 'Your channels',
        surprise: 'Did anything surprise you?',
        surpriseOptions: ['No, as expected', 'A little', 'Quite a bit'],
        schoolLoad: "How's school right now?",
        schoolOptions: ['Chilled', 'Busy', 'Exam week'],
      },
      pinpoint: {
        label: 'Step 2 · Pinpoint & name it',
        title: 'Where do you feel it? Give it a name.',
        help: `Pausing to find where a sensation sits, and putting a word to it, is the heart of the skill — it's how a vague "I feel off" becomes something you actually understand. Tap a spot, flip between front and back, then choose what it feels like. Add as many as you notice, or none if all feels quiet.`,
        front: 'Front',
        back: 'Back',
        allOver: 'All over',
        elsewhere: 'Somewhere else',
        where: 'Where',
        whatLike: 'What does it feel like?',
        howStrong: 'How strong is it?',
        whatDoes: 'And what does it do?',
      },
      result: {
        compareLabel: 'Step 3 · Compare — your read vs your body',
        planLabel: 'Step 4 · Adjust — your plan today',
        swapLabel: 'Your body, your call. Want to shift tempo?',
        copyForCoach: 'Copy what to tell your coach',
        again: 'New tune-in',
      },
    },
    post: {
      title: 'Close the loop',
      steps: ['Look back', 'Sense', 'Learn', 'Recover'],
      lookBack: {
        label: 'Step 1 · Look back',
        title: 'Which tempo did you actually train in today?',
        effort: 'How hard did it actually feel?',
        duration: 'How long was it?',
        sessionType: 'What kind of session?',
      },
      broughtHome: {
        title: 'What did you bring home?',
        help: 'Pick whatever sounds like you today — or none.',
      },
      communicate: {
        title: "Is there anything worth telling someone?",
        copy: 'Copy a line for your coach',
        notToday: 'Not today',
      },
      recoverLabel: "Step 4 · Recover — what your body's asking for now",
    },
  },

  rhythm: {
    title: 'My rhythm',
    rightNow: "Right now you're in",
    aroundDay: 'around day {n} of your cycle',
    mapNotTimetable: "It's a map, not a timetable. 🗺️",
    updateDates: 'Update my dates',
    turnOff: 'Turn this off',
    learnPhases: 'What the four phases can feel like',
    uncertainOne: "You've given BAB **one date** so far, so this is a rough guess. Add another one or two and it gets a lot better.",
    uncertainVariable: 'Your last cycles were **{spread} days apart** at their widest — completely normal at your age, and it means this is a loose read rather than a precise one.',
    uncertainOk: "Based on the **{n} dates** you gave, your cycle runs around **{len} days**. It'll keep shifting — that's normal while it settles.",
    staleTitle: "It's been a while",
    staleBody: "Your last date was more than a full cycle ago, so BAB won't guess where you are — guessing would just be making something up. Pop in your latest date and the map comes back.",
    staleCta: 'Add my latest date',
    notYetTitle: "Nothing to track yet — and that's completely normal",
    notYetBody: 'Bodies begin on their own timeline, anywhere across these years. When yours starts, you can switch this on and BAB will start mapping your rhythm.',
    notYetCta: "I've started — set it up",
    offTitle: 'This part is switched off',
    offBody: 'You chose not to share your cycle, and everything else in BAB works exactly the same. You can switch it on any time in Settings — no rush, and no reminders from us.',
  },

  me: {
    title: 'Me',
    readingTitle: 'Your read keeps getting sharper',
    readingLabel: 'How well you read yourself',
    collectingTitle: "Still learning how you're built",
    collectingBody: 'Every check-in is a dot. Once there are enough of them, the dots start showing patterns that are yours alone.',
    collectingCount: '{done} of {total} check-ins',
    collectingLeft: 'About {n} more and the first patterns start to appear.',
    insightCaveat: "These are ideas, not facts. You're the expert on you: keep the ones that feel true, and question the ones that don't.",
    insightYes: 'That sounds like me',
    insightNo: "Doesn't fit",
    storyTitle: 'Your weekly story',
    storyBody: 'Something you can hand to a coach or a parent',
    storyCta: 'Put one together',
    storyLocked: 'Unlocks after your first full week',
  },

  story: {
    title: 'My week',
    chooseTitle: 'What goes in?',
    chooseHelp: 'Nothing is shared until you say so. Tap to add or remove — the card below updates as you go.',
    blocks: {
      tempos: 'My tempos',
      temposHelp: 'Which gear you trained in each day',
      spots: 'Where I felt things',
      spotsHelp: 'The spots that came up most, and what they felt like',
      energy: 'My energy through the week',
      energyHelp: 'A simple line — no numbers, no score',
      note: 'What I wrote',
      noteHelp: 'The note you left after training',
      cycle: 'My cycle',
      cycleHelp: 'Which phase you were in — off unless you turn it on',
    },
    cycleNote: "Your cycle is the most private thing BAB holds. It's never included automatically, it never travels with anything else, and turning it on here applies to **this card only** — never to the next one.",
    previewTitle: "This is exactly what they'll see",
    previewHelp: 'No live link, no dashboard, no login. Just this picture — so what you send is all they get.',
    send: 'Send this',
    keep: 'Keep it for me',
    saidTitle: "And here's how to open the conversation",
    saidHelp: 'Copy this if it helps — or say it your own way, which is better.',
    copyWords: 'Copy these words',
    emptyState: "Nothing selected yet — pick at least one thing above, and it'll appear here.",
  },

  onboarding: {
    welcomeTitle: 'This is about learning to read yourself',
    welcomeBody: 'Most sports apps measure you from the outside and tell you what to do. BAB does the opposite: it helps you learn what your own body is telling you — so you know when to push, when to rest, and how to say it out loud.',
    isTitle: 'What this is',
    isNotTitle: "What this isn't",
    letsGo: "Let's go",
    continue: 'Continue',
    consentTitle: 'Before anything else',
    consentHelp: "You're under 18, so we need two yeses — yours and a parent's or guardian's. Read them together if you can.",
    ageTitle: 'How old are you?',
    ageHelp: 'This changes how BAB talks to you and how detailed the body map is — nothing else.',
    sportTitle: 'What do you play, and when?',
    sportHelp: 'So BAB knows which days to expect a check-in — and stays quiet on the others.',
    sportLabel: 'Your sport',
    daysLabel: 'Training days',
    setUpLater: "I'll set this up later",
    rhythmTitle: 'Do you have your period yet?',
    rhythmBody: 'If you do, BAB can use it as the backdrop behind all your other signals — the thing almost no sports app does. It\'s yours, it stays yours, and you can switch it off any time.',
    rhythmYes: 'Yes, I have it',
    rhythmYesHelp: 'BAB will map your phases from the dates you give it',
    rhythmNotYet: 'Not yet',
    rhythmNotYetHelp: 'Completely normal — bodies start on their own timeline, anywhere across these years',
    rhythmSkip: "I'd rather not say",
    rhythmSkipHelp: 'Fine too. Everything else works exactly the same',
    datesTitle: 'When did your last periods start?',
    datesHelp: 'Best guess is fine. Even one date lets BAB start; two or three make it better. At your age cycles are often still settling, so BAB treats this as a rough map, never a schedule.',
    dateMostRecent: 'Most recent',
    datePrevious: 'The one before',
    dateBefore: 'And before that',
    contraceptionTitle: 'Are you on any hormonal contraception?',
    contraceptionHelp: 'Pill, implant, coil, patch, injection. About half of athletes are, and it changes what your signals mean — so BAB needs to know to read them properly.',
    whyDatesTitle: `Why BAB asks for dates instead of "which phase are you in?"`,
    whyDatesBody: "Because working it out from dates is the reliable way — guessing your own phase isn't, especially in the first years. You'll never have to classify yourself.",
    cyclePrivacy: 'This is the most private thing here. Your cycle is never shared with a coach, never shown to anyone, and never included in anything you send — unless you tick it yourself, every single time.',
    doneTitle: "That's it — about 90 seconds",
    doneBody: 'Here\'s what BAB knows about you. You can change any of it later, in Settings.',
    doneCta: 'Start my first tune-in',
  },

  settings: {
    title: 'Settings',
    profile: 'Profile',
    rhythm: 'My rhythm',
    privacy: 'Privacy and data',
    notifications: 'Reminders',
    help: 'Help',
    exportData: 'Export my data',
    deleteAccount: 'Delete my account',
    deleteConfirm: 'Really delete everything? There is no going back.',
    language: 'Language',
  },

  common: {
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    offline: "You're offline — what you write is saved here and sends itself later.",
    loading: 'One moment…',
  },

  disclaimer:
    "BAB helps you understand yourself — it doesn't replace your coach, a physio or a doctor, who can see and check things a screen can't. If anything ever feels wrong with your body or your mind, tell a trusted adult. That's always the strong move.",
}
